server:
  port: 8080

dubbo:
  application:
    name: user-consumer
  registry:
    address: zookeeper://39.101.141.231:2181
  consumer:
    timeout:
  scan:
    base-packages: com.atguigu.gmall.controller

logging:
  level:
    root: info


